services:

  jzero-execution:
    image: ethereum/client-go:v1.14.11
    user: root
    entrypoint: /root/geth-script.sh
    command:
      - "--datadir=/datadir/geth"
      - "--networkid=${NETWORK_ID}"
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwt.hex
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,engine,web3,net
      - --http.port=8545
      - --http.corsdomain=*
      - --http.vhosts=*
      - --port=32302
      - --verbosity=3
      - --nodiscover
    volumes:
      - ./data:/datadir
      - ./geth-script.sh:/root/geth-script.sh
      - ./config:/config
    ports:
      - 32302:32302
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  jzero-consensus:
    image: sigp/lighthouse:v5.3.0
    user: root
    entrypoint: /root/lighthouse-script.sh
    depends_on:
      - jzero-execution
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://jzero-execution:8551
      - --execution-jwt=/config/jwt.hex
      - --testnet-dir=/config
      - --http-allow-sync-stalled
      - --disable-peer-scoring
      - --http
      - --http-address=0.0.0.0
      - --http-port=5502
      - --disable-packet-filter
      - --target-peers=${TARGET_PEERS}
      - --enr-address=${NODE_PUBLIC_IP}
      - --enr-udp-port=9900
      - --enr-tcp-port=9900
      - --port=9900
      - --disable-enr-auto-update
      - --prune-blobs=false
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
      - ./lighthouse-script.sh:/root/lighthouse-script.sh
    ports:
      - 0.0.0.0:9900:9900/tcp
      - 0.0.0.0:9900:9900/udp
      - 0.0.0.0:5502:5502/tcp
      - 0.0.0.0:5502:5502/udp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

